### ISSUE TITLE
Adding FAQs

### ISSUE THREAD

**Issue by AswaniBolisetti** [Vimall03/Alimento#101]
@Vimall03 
I would like to add FAQs
could you please assign me this

**Comment by Vimall03** [comment]
@AswaniBolisetti This issue is fixed in #99 
Closing this as Duplicate of #79

**Comment by AswaniBolisetti** [comment]
@Vimall03 I mean i want to add a button - load more FAQs, by clicking on it, few more faqs will be displayed
