### ISSUE TITLE
[FEAT] Feature Request: Add Project Description to GitHub "About" Section

### ISSUE THREAD

**Issue by 5odead** [Vimall03/Alimento#102]
### Is your feature request related to a problem? Please describe.
Yes, the repository currently lacks an "About" section on its GitHub page. This makes it difficult for new visitors or potential contributors to understand what the project is about and what its purpose is.
 
![Screenshot_20241013_224947](https://github.com/user-attachments/assets/76db67f1-e6c8-47d0-8ea5-2c3f663b41a1)

### Describe the solution you'd implement
I suggest that the repository owner fills in the "About" section with the following description:
> "Alimento is a platform that connects home chefs with food lovers. It lets chefs offer homemade dishes, and users can easily order and enjoy fresh meals delivered to their homes."

### Describe alternatives you've considered
The README is quite detailed so its good but there's no alternative to it.

### Additional context
Including a brief description in the "About" and "Description" section will make the project more approachable and could attract more contributors or users interested in the platform.

(Please add gssoc-ext 24 and hacktoberfest label and level label)

**Comment by Vimall03** [comment]
Hey @5odead, I don't think you will be able to access the about section of the repo since you will need collaborator access to it, I wont be able to give you collaborator access as per the guidelines of GSSoC'24 

Closing this issue as unplanned.
