### ISSUE TITLE
[FEAT] The header section needs a better visual effect and logo and button position need to be relocated.

### ISSUE THREAD

**Issue by aman8042** [Vimall03/Alimento#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd implement**

**Describe alternatives you've considered**

**Additional context**

**Comment by Vimall03** [comment]
Hey @aman8042, Can you describe more about this ?

Are you talking about the navbar ?

**Comment by aman8042** [comment]
Yes,i think the navbar needs a bit of upgrade.

**Comment by Vimall03** [comment]
Will you changing the navbar of all the pages or just the landing page?

**Comment by aman8042** [comment]
For an instance just the navigation bar, if i find any necessary change then only i'll let you know.

**Comment by Vimall03** [comment]
@aman8042, I will assign this issue, but i will give an appropriate level based in the PR

**Comment by Vimall03** [comment]
@aman8042, I'm closing this issue since this will get fixed in the complete UI redesign that we are doing and this would be an unnecessary change. Thankyou for understanding.

**Comment by aman8042** [comment]
@Vimall03 Will be waiting for the new UI.
