### ISSUE TITLE
[FEAT] Redesign home.php (UI fix)

### ISSUE THREAD

**Issue by Vimall03** [Vimall03/Alimento#108]
Redesign the UI of the home.php page to make it visually appealing. This is a level 2 issue, We expect a good design for the page.
Please comment below if you are interested in taking up this issue. 

![image](https://github.com/user-attachments/assets/b2db79f4-e70f-43a4-a590-b52e0c635a80)

**Comment by SumitSahu44** [comment]
hey @Vimall03 in the given figma the landing page design you gave and in this repo im working on home.php page where all restaurant show so what can i do work on home.php or create a landing page

**Comment by Vimall03** [comment]
@SumitSahu44 You can use the same color and design elements form this design.

**Comment by SumitSahu44** [comment]
![image](https://github.com/user-attachments/assets/9d244217-e566-4df8-bc89-7099a901fbe4)
is these good for home page after registration

**Comment by Vimall03** [comment]
@SumitSahu44 This looks good. Please use the font mentioned in my previous comment

**Comment by SumitSahu44** [comment]
hey @Vimall03 i pushed my PR please check it
