### ISSUE TITLE
[FEAT] Redesign & Fix NavBar in all the pages. 

### ISSUE THREAD

**Issue by Vimall03** [Vimall03/Alimento#109]
There is a inconsistency in Navbar design throughout the site. We need to implement a standard Navbar with broken link fixes. 
This is a level 2 issue, So the design and implementation needs to be visually appealing and userfriendly 

**Screenshot of some inconsistent navbars :**

![image](https://github.com/user-attachments/assets/8369bc04-0274-48ae-a377-00f70fd8247c)

![image](https://github.com/user-attachments/assets/439ca236-1d61-4c93-8939-118d51b33a91)

![image](https://github.com/user-attachments/assets/a599a236-99f5-4d44-bb41-968408a839c1)

Comment on this issue if you are interested in contributing.

**Comment by Sourabh782** [comment]
hii @Vimall03, can i work on these issues?

**Comment by Vimall03** [comment]
Sure @Sourabh782, Please share me a navbar design that you are planning to implement.

**Comment by Sourabh782** [comment]
@Vimall03, ill share design tommorow, but for idea:
1. proper alignment of button
2. dark mode toggle button issue (in light mode switch is not visible)
3. adding interactivity using css
4. improving design (inputs)

**Comment by Vimall03** [comment]
@Sourabh782 No issues, would you be able to implement tailwind css ?

**Comment by Vimall03** [comment]
Great

**Comment by Sourabh782** [comment]
So @Vimall03 can I work on it?

**Comment by Vimall03** [comment]
Yes, you can get started

**Comment by Vimall03** [comment]
Hey, @Sourabh782 Have you made any progress ?

**Comment by Sourabh782** [comment]
Hello @Vimall03, yes have done some work on them will share ss soon

**Comment by Sourabh782** [comment]
hey @Vimall03 check these changes: 

![profile php](https://github.com/user-attachments/assets/e5eef8b8-6fb6-4497-8797-fda38c56d8fb)

i have made same navbar for 
1. profile page
2. home page
3. change password page
4. edit profile page

**Comment by Vimall03** [comment]
@Sourabh782, Can you fix the rendering of the logo. 
Try to implement something like this. The code for this navbar can be found in index.php

![image](https://github.com/user-attachments/assets/e65f2919-00af-416b-ac48-10e63ddbe8d2)

**Comment by Sourabh782** [comment]
> @Sourabh782, Can you fix the rendering of the logo. Try to implement something like this. The code for this navbar can be found in index.php
> 
> ![image](https://private-user-images.githubusercontent.com/109758195/378176015-e65f2919-00af-416b-ac48-10e63ddbe8d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjA4NDYsIm5iZiI6MTcyOTQyMDU0NiwicGF0aCI6Ii8xMDk3NTgxOTUvMzc4MTc2MDE1LWU2NWYyOTE5LTAwYWYtNDE2Yi1hYzQ4LTEwZTYzZGRiZThkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMDM1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGYxZjQ2YWIxMmFhOGVhNWVmY2UzMTRkNGI5Y2MyY2RlNzMyOTg0MDYxYzc1NjA4ZjI0NWNjNWZiMGMzZDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fqA3doZ1-MYDNdvSQX6lLptaeCW5Q0KRGbamACS7I_Q)

Sure 👍

**Comment by Sourabh782** [comment]
Hii @Vimall03  like this?
![image](https://github.com/user-attachments/assets/cf2e0dda-dc7a-4ab3-ac3f-cf74b8c46113)

**Comment by Vimall03** [comment]
Yes this looks good

**Comment by Sourabh782** [comment]
> Yes this looks good

Ok I'll implement same for other pages

**Comment by Sourabh782** [comment]
@Vimall03  check these:
profile.php
![profile](https://github.com/user-attachments/assets/7ea191ec-a4c0-47d5-a490-822cd5f555f1)

checkout.php
![checkout php](https://github.com/user-attachments/assets/d482c215-8a2f-45d9-835c-9db342937bc2)

changepassword.php
![change password](https://github.com/user-attachments/assets/838e5cb0-d877-44b8-ac09-2914007fd252)

order.php
![orders](https://github.com/user-attachments/assets/041b42af-2625-4756-9f8f-330afdbc818c)

**Comment by Vimall03** [comment]
@Sourabh782  Is there any dropdown for logout Function and other options like track order ?

**Comment by Sourabh782** [comment]
> @Sourabh782 Is there any dropdown for logout Function and other options like track order ?

yes both logout and track order are accecible from profile button (right most)

**Comment by Sourabh782** [comment]
![image](https://github.com/user-attachments/assets/472c690c-2ea4-4277-9c38-0053d1b939e1)

**Comment by Vimall03** [comment]
Okay, Looks good 👍

**Comment by Sourabh782** [comment]
> Okay, Looks good 👍

There's a minor bug I'll send pr after fixing it
