### ISSUE TITLE
[Feat] Redesign Landing Page UI (index.html) to a Visually Appealing Design

### ISSUE THREAD

**Issue by Vimall03** [Vimall03/Alimento#110]
Looking for contributors to redesign the complete UI of the landing page (index.html) to make it visually appealing and engaging for users. You are free to get creative and implement any design that enhances the look and feel of the page.

**Guidelines:**

- You may use CSS frameworks like Bootstrap to speed up your work.
- This is a Level 2 issue, so we expect a well-thought-out design that is responsive and visually engaging.
Before proceeding with development, please submit your design for approval.

**How to Contribute:**

- Comment below if you're interested in contributing.
- Share a preview or wireframe of your design for approval before starting development.

Looking forward to your creative designs!

**Current Page:** 

![image](https://github.com/user-attachments/assets/2345f84e-931d-4c70-9463-2f3d16d30944)

**Comment by ArchanRD** [comment]
@Vimall03 I am interested! I would like to give a suggestion. Instead of writing plain css, we can use tailwindcss.

## Why to use tailwind?
- Speedy developement
- Modern design
- Highly customizable
- Easy to setup ( from a contributor perspective )
- Responsiveness

**Comment by Vimall03** [comment]
@ArchanRD Yes Tailwind would be a great choice. Please share me the design you are going for, it doesn't need to have the elements or color pallet of the current design. You are free to implement a completely new design.

**Comment by ArchanRD** [comment]
@Vimall03 Let me get back to you with the design. Please give me sometime.

**Comment by Vimall03** [comment]
Sure, take your time

**Comment by Sarthakkashyapp** [comment]
hi @Vimall03 I am ready to do this.

**Comment by ArchanRD** [comment]
@Vimall03 The design is ready. I have done my best to create a design in a short time. Though while development this design can be enhanced and can alter with the color pallete.

Figma: https://www.figma.com/design/hbfVm94AuIo6aPujnGOhha/Alimento?node-id=0-1&t=i65X6t77cosbSHEx-1

**Comment by Vimall03** [comment]
@ArchanRD Looks good, You can get started

**Comment by ArchanRD** [comment]
Yeah! Sounds good.

**Comment by ArchanRD** [comment]
@Vimall03 Instead of `index.html` can we create `index.php`, so that we can make sure that session works for buttons in navbar.

**Comment by Vimall03** [comment]
Yes, that would be better

**Comment by ArchanRD** [comment]
@Vimall03 Here's the progress! 
1. Integrated tailwindcss using npm. ( I will update the readme for tailwindcss setup )
2. Create fully responsive navbar

preview:

https://github.com/user-attachments/assets/b28017fc-5d12-4ff2-9852-76788515c82a

**Comment by Vimall03** [comment]
@ArchanRD  Cool, Also can you share the font that you will be using ?

**Comment by ArchanRD** [comment]
Sure! The font is poppins from google fonts

**Comment by ArchanRD** [comment]
The button text for " Register as vendor" is too long for a button. I would suggest to add a section in the landing page. We can do something like this.
![image](https://github.com/user-attachments/assets/08f104f7-098c-4d91-8d3d-1c0184d1e8ca)

**Comment by Vimall03** [comment]
@ArchanRD Okay, looks good

**Comment by ArchanRD** [comment]
Hey @Vimall03 Could you please promote this issue to level 3. Though it is a single page but it is taking a lot to build it + responsive. I would really appreciate if you could do this!

**Comment by VanshGarg06** [comment]
I have done the alignment of the Home page but unable to create pull request and merge pull request

**Comment by Vimall03** [comment]
Hey @ArchanRD I understand, I will review the code at the time of PR and push it to level 3 if required. Don't worry about it for now.

**Comment by Vimall03** [comment]
@VanshGarg06, You are supposed to open an issue that you would like to work and get assigned to it first before you open a PR as per the guidelines of GSSoC'24.
