### ISSUE TITLE
[BUG]: Responsiveness issue

### ISSUE THREAD

**Issue by Sourabh782** [Vimall03/Alimento#111]
**Describe the bug**

**To Reproduce**
1. in desktop mode site is partially cut :
![Screenshot 2024-10-15 213754](https://github.com/user-attachments/assets/460624cd-08a0-4aec-8aac-83c278da6b32)

2. in mobile mode, navbar button is not working
![image](https://github.com/user-attachments/assets/c19f171b-d695-4fd7-a45a-0168de03304c)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by Vimall03** [comment]
@Sourabh782, I expect this to be fixed in #108 & #109
