### ISSUE TITLE
[FEAT] UI update for vendor login/signup

### ISSUE THREAD

**Issue by Sourabh782** [Vimall03/Alimento#112]
**Is your feature request related to a problem? Please describe.**
while working on vendor page, i got problems cause i was entering wrong password

**Describe the solution you'd implement**
i wanted to ass a hide/show password toggle button to make it easier to verify password and reduce unwanted DB calls

**Additional context**
![Screenshot 2024-10-15 213512](https://github.com/user-attachments/assets/50815a02-d320-47a9-9f2e-783c31577062)
![Screenshot 2024-10-15 213455](https://github.com/user-attachments/assets/5fdb56ca-cbda-4e46-8c62-967edcb396dc)

**Comment by Sourabh782** [comment]
> @Sourabh782, I will update you on this issue in a couple of days. An UI update might look good on these pages. Work on your other issues until then

So like how about working on ui redesign?

**Comment by Sourabh782** [comment]
Sure @Vimall03 👍👍

**Comment by VanshGarg06** [comment]
Hi! I have also worked for ecommerce on PHP. Kndly assign this issue to me.

**Comment by Vimall03** [comment]
Hi @VanshGarg06, This issue was opened by another contributor. Please open a new issue if you are interested in contributing.

**Comment by Sourabh782** [comment]
hello @Vimall03 can i work on this issue now?

**Comment by Vimall03** [comment]
@Sourabh782 Please send me the Design before you start implementing on code. Also, Please check for any UI bugs before pushing the code to the repo.

**Comment by Sourabh782** [comment]
> @Sourabh782 Please send me the Design before you start implementing on code. Also, Please check for any UI bugs before pushing the code to the repo.

Yes @Vimall03, I'll send proper recording this time

**Comment by Sourabh782** [comment]
Hey @Vimall03 can I complete redesign it like properly from tailwind css only ?

**Comment by Vimall03** [comment]
Yes, Please share me the figma design first or else I'll send a template so that you can follow the design in the template.

**Comment by Sourabh782** [comment]
> Yes, Please share me the figma design first or else I'll send a template so that you can follow the design in the template.

can you share template? actually i m not very finilar with figma

**Comment by Vimall03** [comment]
Cool, No worries I'll send a design soon.

**Comment by Vimall03** [comment]
@Sourabh782, Look into this - 
https://www.figma.com/design/pFceSIHmBrZXrLrCHphtnt/Login---UX%2FUI-Design-%7C-Free-UI-KIT-(Community)?node-id=0-1&node-type=canvas

**Comment by Sourabh782** [comment]
yes looks great, ill implement it, can i get that mointain image?

**Comment by Vimall03** [comment]
You can download the image directly from the Figma design. Click on the image, then find the export option in the right-side panel. Choose your preferred image type under 'Export' and click 'Export' to download it. 
Learning the basics of Figma will be helpful during development.

**Comment by Sourabh782** [comment]
> You can download the image directly from the Figma design. Click on the image, then find the export option in the right-side panel. Choose your preferred image type under 'Export' and click 'Export' to download it. Learning the basics of Figma will be helpful during development.

Okk I'll work on it, and sorry for extra trouble 🥲

**Comment by Vimall03** [comment]
No trouble at all! This whole process is a great learning experience, so keep at it! Every step you take helps build your skills—you're doing great 😊

**Comment by Vimall03** [comment]
@Sourabh782 Have you made any progress ?

**Comment by Sourabh782** [comment]
> @Sourabh782 Have you made any progress ?

hello @Vimall03, yes i am working on it only, and will send pr till evening :))

**Comment by Sourabh782** [comment]
@Vimall03 can you check these? 
![Screenshot 2024-10-25 143050](https://github.com/user-attachments/assets/dd14029b-f7f7-41ac-b239-5da499b1262b)

![Screenshot 2024-10-25 143038](https://github.com/user-attachments/assets/4c2992c6-3a8d-43da-89af-2826ff336c46)

![Screenshot 2024-10-25 143101](https://github.com/user-attachments/assets/c2a7a761-8dc9-4905-a637-8c1b8952543e)

**Comment by Vimall03** [comment]
Yeah looks good, Make sure all the CRUD operations are working before the PR

**Comment by Sourabh782** [comment]
> Yeah looks good, Make sure all the CRUD operations are working before the PR

i tried and its working fine. should i send recording?

**Comment by Vimall03** [comment]
No not necessary
