### ISSUE TITLE
[BUG] Website shift left

### ISSUE THREAD

**Issue by snehasharma200303** [Vimall03/Alimento#115]
**Describe the bug**

The content shifts to the left, creating a visible gap on the right side of the screen, disrupting the layout.

**To Reproduce**
1. Go to the website '[website URL]'.
2. Resize the browser window by dragging the edge to reduce/increase the width.
3. Scroll down the page to observe the content layout.
4. Notice that the entire website content shifts to the left, leaving a gap on the right side.

**Expected behavior**

The content should remain centered or properly aligned within the viewport, regardless of user interaction or browser size.

**Screenshots**

![{6E8A7F54-EEDF-4A4A-8731-B50D68873629}](https://github.com/user-attachments/assets/c58b9cc3-7e21-4327-8cd7-cf3f414db508)

![{4014BBC7-3572-4191-BD53-246D72BC6DD0}](https://github.com/user-attachments/assets/30fdca53-d8ab-4888-afd1-d9b3f76f4949)

**Desktop (please complete the following information):**
 - OS: [Your operating system, e.g., Windows 10, macOS Monterey, Ubuntu 20.04]
- Browser: [The browser you're using, e.g., Chrome, Firefox, Safari]
- Version: [The version of the browser, e.g., 116.0.5845.110]

**Additional context**

"The issue occurs on all pages across the website."

**Comment by Vimall03** [comment]
hi @snehasharma200303, This issue will be fixed in #110
