### ISSUE TITLE
[FEAT] Chatbot Fix

### ISSUE THREAD

**Issue by snehasharma200303** [Vimall03/Alimento#116]
**Is your feature request related to a problem? Please describe.**

The chatbot box on the website is too large, taking up a significant portion of the screen, which may negatively affect the user experience. The size of the box makes it difficult for users to interact with other parts of the page, especially on smaller screens. 

Additionally refress  button does not working .

**Describe the solution you'd implement**

Reduce the size of the chatbot box to about 20-25% of the screen height and width.
Add a responsive design so that the chatbot box scales down on smaller screens (e.g., mobile devices).
Consider adding a collapse/expand functionality so the box is minimized when not in use, expanding only when clicked by the user.
Ensure the box is properly aligned and centered within the viewport without interfering with other website elements.

**Describe alternatives you've considered**

**Additional context**

![{7871C01E-6E3E-492B-BD8E-6C1E0AD11A7A}](https://github.com/user-attachments/assets/bfe2bf18-820e-457a-94cb-e0a032f76ca3)

After refresing 
 
![{17A09C82-F29A-4DE5-B12C-69C8FB55D8B0}](https://github.com/user-attachments/assets/0b9425b2-557d-4769-b001-a26aa499b197)

**Comment by Vimall03** [comment]
@snehasharma200303, Great You can get started!

**Comment by snehasharma200303** [comment]
okky. Thanks

**Comment by snehasharma200303** [comment]
Hello , I wanted to highlight some concerns regarding the chatbot in your project . The chatbot seems to be taken from a predefined chatbox website, limiting customization, not responsive, and cannot do modification. 
I have created a new chatbox that is fully customizable and  much responsive than that , allowing for easier modifications.
But i have not pull it because there is some minute issue as website needs some modification on behalf of that i will change ..
if you want i PR it .

**Comment by Vimall03** [comment]
@snehasharma200303, This chatbot was embedded using a 3rd party service. The website UI is currently being fixed. 
The new chatbot that you have implemented, is it working ? and how is this implemented ?

**Comment by snehasharma200303** [comment]
Yes , Chatbot i have implement it is much better than that 3rd party service chatbot. 
This  is somewhat normal chatbot using js , and I have add some question and answer accordingly   it will answer , if it found  question out of the question bank it will answer default which i have already been given.  i can add more question and  answer. 
So that for now it will quite responsive.

**Comment by Vimall03** [comment]
okay that sounds good, I will push this issue to level 2 since you have worked on additional issues as well. However I need you to make changes to the UI of the Chatbot. I see that it inherits the colors of the current landing page, but we are soon changing the landing page to this design - https://www.figma.com/design/hbfVm94AuIo6aPujnGOhha/Alimento?node-id=0-1&t=i65X6t77cosbSHEx-1
So it would nice if the chatbot adapts the colors of the new design.

**Comment by snehasharma200303** [comment]
okky, i will change it ..

**Comment by Vimall03** [comment]
@snehasharma200303, The PR for the new layout is opened. We are yet to resolve some conflicts. I will update you once its done.

**Comment by Vimall03** [comment]
@snehasharma200303 The UI of the landing page is updated. Please sync your fork to view the changes

**Comment by snehasharma200303** [comment]
okky.

**Comment by snehasharma200303** [comment]
I have  PR  it.. PLease check.. 
If need any change or correction please do let me know .. I will fix it.. 
And  Let me know if there’s anything else to do.

**Comment by snehasharma200303** [comment]
I have PR it again.. could you please check
