### ISSUE TITLE
[FEAT] adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Vimall03/Alimento#118]
I want to add a page to showcase all the contributors of this website. @Vimall03 can you please assign me this issue.

**Comment by Vimall03** [comment]
@T-Rahul-prabhu-38, That would look good. How are you planning to implement this ? Will the contributors list update dynamically ?

**Comment by T-Rahul-prabhu-38** [comment]
I have done it for 2 other repos till now , its done by calling an github API key

**Comment by T-Rahul-prabhu-38** [comment]
it will be realtime update as well.

**Comment by Vimall03** [comment]
@T-Rahul-prabhu-38 Great, Please make sure that the design of this page matches the color and design elements in this design - https://www.figma.com/design/hbfVm94AuIo6aPujnGOhha/Alimento?node-id=0-1&node-type=canvas

**Comment by Vimall03** [comment]
I will push this issue to level 2 based on your PR if necessary

**Comment by T-Rahul-prabhu-38** [comment]
sure ill do that.
