### ISSUE TITLE
[FEAT] fixing the UI

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Vimall03/Alimento#121]
The homepage UI is completely broken.
<img width="738" alt="Screenshot 2024-10-17 at 6 38 24 PM" src="https://github.com/user-attachments/assets/f47af1e9-5eed-427e-81ba-5481bcbcd2d3">

@Vimall03 if u assign me i could fix it.

**Comment by Vimall03** [comment]
@T-Rahul-prabhu-38 This is already being handled in the issue #110
