### ISSUE TITLE
[FEAT]Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Vimall03/Alimento#123]
I want to add multi language support system to the website which can help us understand in their native language.
@Vimall03 can you assign me this issue.

**Comment by Vimall03** [comment]
@T-Rahul-prabhu-38 How are you planning to implement this ?

**Comment by T-Rahul-prabhu-38** [comment]
google API

**Comment by Vimall03** [comment]
Okay, You can get started.
