### ISSUE TITLE
Addition of splide js to show the reviews in slideshow and change of color of text in "frequently asked question"

### ISSUE THREAD

**Issue by Shirisha-16** [Vimall03/Alimento#128]
Showing the reviews with slideshow.
![Screenshot 2024-10-18 211137](https://github.com/user-attachments/assets/965fd3fe-ecda-4549-811a-8efbb5ac38ab)

Questions are not visible due to the white color . Want to change the color of text under "frequently asked questions"
![Screenshot 2024-10-18 211730](https://github.com/user-attachments/assets/42e843e2-1726-42ff-8d3c-669e35e48b73)
i want to work on this issues
@Vimall03 assign me this work with the labels gssoc-ext, hacktoberfest-accepted and level according to the issue.

**Comment by Vimall03** [comment]
Hi @Shirisha-16, There was a recent UI update that was made to the landing page. Please update your fork and check the site again. Let me know if you would like to make any changes to the reviews section of the new landing page.

**Comment by Shirisha-16** [comment]
@Vimall03 is there any problem with index.html page . I am unable to see that page

**Comment by Vimall03** [comment]
@Shirisha-16 In the recent UI update, the index.html file is changed to index.php
You will need a xampp / wampp server to run the project.

**Comment by Vimall03** [comment]
@Shirisha-16 please let me know if you are still interested in contributing
