### ISSUE TITLE
Enhance the README text

### ISSUE THREAD

**Issue by Abankita** [Vimall03/Alimento#13]
@Vimall03 I would like to propose an update in the README file for the Alimento project. The current README is a nice overview, and I feel that we can make it even better by including the following:

1. Adding a "Why Choose Alimento?" section – Here, we will highlight the unique benefits of the platform.

2. The Contributing section needs betterment – better directions for willing contributors.

3. Emojis – To make the document interesting.
Then, this will help improve the user understanding, invite more contributors, and so on. 

Additionally, I would request you to provide the link to the website in the about section of the repository. This will be of great help to other fellow contributors.

**Comment by Vimall03** [comment]
Sounds good @Abankita, Thankyou for your willingness to contribute to this repository!
I will assign it to you once @aditiverma-21 completes issue #8, as it will give you more context for the "set-up" section. You can get started once I assign it to you.
