### ISSUE TITLE
Addition of feedback form

### ISSUE THREAD

**Issue by shauryaq05** [Vimall03/Alimento#131]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd implement**

**Describe alternatives you've considered**

**Additional context**

**Comment by Vimall03** [comment]
@shauryaq05 can you give a description of this issue ?

**Comment by shauryaq05** [comment]
The feedback helps the organisation to get views from the users helping in
further improvement of the website.

**Comment by Vimall03** [comment]
@shauryaq05 How will you implement this ? Where will you store the feedbacks ?

**Comment by shauryaq05** [comment]
My initial idea was to display the feedback form at the footer of the
landing page, but since I think it can be better used .I leave this to you
for its best possible case ***@***.***

**Comment by Vimall03** [comment]
@shauryaq05 I don't think a feedback form is required at least at the current stage of the project. I'm closing this issue. Thankyou for understanding.
