### ISSUE TITLE
[BUG]: Non uniform navbar and css breaks

### ISSUE THREAD

**Issue by ArchanRD** [Vimall03/Alimento#142]
**Describe the bug**
When I pulled the recent changes, I saw that the navbar is not according to the updated design. Second thing, in the navbar, when you click on orders page, the old orders page is linked whereas new one is already added `new_track_order.php`.  

On pin_search.php the navbar is not updated. 
![image](https://github.com/user-attachments/assets/8680d19d-757f-447a-abc6-d38200b1e0ca)

Also messed up the new navbar while adding extra button. 
![image](https://github.com/user-attachments/assets/2fb08890-d38c-4645-89b1-23f5b3e870cb)

**To Reproduce**
1. Go to 'index.php'
2. Navigate to every link in navbar
3. See CSS breaks and non uniformity of navbar

**Expected behavior**
The navbar should be same on all the pages. The navbar should redirect to updated pages rather than old ones. (here orders.php in context )

**Screenshots**

https://github.com/user-attachments/assets/a9a6e7e0-e600-45b1-b6c2-e51924bf02ca

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [brave]
 - Version []

**Additional context**

**Comment by Vimall03** [comment]
@ArchanRD, I have reverted the PR. I will assign this to you as level 2
