### ISSUE TITLE
pr-checker is not workig on you'r repo!!

### ISSUE THREAD

**Issue by smog-root** [Vimall03/Alimento#146]
A github workflow named pr-checker is not working on you'r repo!! 

i can fix that!! @Vimall03 

Add gssoc-ext with level and hacktoberfest-accepted labels!!

![Screenshot 2024-10-22 073554](https://github.com/user-attachments/assets/c23cfff5-f133-4745-923d-bde7cf42269e)

**Comment by Vimall03** [comment]
@smog-root I will assign this to you once you complete the PR for your existing issue.

**Comment by Vimall03** [comment]
@smog-root You can get started

**Comment by smog-root** [comment]
![Screenshot (34)](https://github.com/user-attachments/assets/1f438482-5b26-4238-a242-425690bc0510)
