### ISSUE TITLE
[BUG] : Alignment of the Home page elements

### ISSUE THREAD

**Issue by VanshGarg06** [Vimall03/Alimento#157]
**Describe the bug**
Alignment of the Home Page is left aligned which should aligned at center that makes an appealing look of webpage.

**To Reproduce**
1. Go to Home Page "index.html"
2. Scroll over the page the whole web page alignment is left aligned

**Expected behavior**
The alignment of the home page section is left aligned at present which should be center aligned.

**Screenshots**
![Alimento home page](https://github.com/user-attachments/assets/b5831f06-a3cb-4c86-9d54-da4c7ac7e366)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome
 - Version: 22

**Additional context**
The sections of the home page are left aligned which degrades the user experience.
Please assign this issue to me under hacktoberfest and gssoc-ext with level 2 necessary labels.

**Comment by Vimall03** [comment]
@VanshGarg06 You are running a older version of the project. The homepage is fixed and the entire UI has been changes. Please update your fork / sync the project for the latest changes.
