### ISSUE TITLE
[BUG]: Overlapping of the word on the Home Page Hero Section

### ISSUE THREAD

**Issue by VanshGarg06** [Vimall03/Alimento#158]
**Describe the bug**
The words of the main line are overlapping on the Hero section of the Home Page.

**To Reproduce**
1. Go to Home Page on "index.html"
2. Scroll to Hero Section of Home Page

**Expected behavior**
The main line of the Hero Section of the Home page the words are overlapping.

**Screenshots**
![Alimento home page savoury alignment](https://github.com/user-attachments/assets/133b5418-8618-4b04-8da8-5b52e0e99a20)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Google Chrome
 - Version 22

**Additional context**
The overlapping of the words is there in the Hero section of the Home page which degrades the user experience.
Please assign this issue to me under hacktoberfest and gssoc-ext with level 2 by providing the necessary labels.

**Comment by Vimall03** [comment]
@VanshGarg06 This has already been fixed. The UI has been updated. Please update your fork for the latest changes
