### ISSUE TITLE
[Documentation] I want to add the UI link of the prototype of the website in the documentation

### ISSUE THREAD

**Issue by NumlStudentSE** [Vimall03/Alimento#159]
I want to add the UI link of the prototype of the website in the documentation so UI/UX designers and users can interact with it and contribute in the front end. I also want to add the screenshots of the UI of the website to be included in the documentation page.

Please assign this issue to me @Vimall03

**Comment by Vimall03** [comment]
@NumlStudentSE The site is not hosted so i dont think its possible to paste the UI link or make it accessible to anyone.
