### ISSUE TITLE
[BUG] : Sign In button not working on Home Page

### ISSUE THREAD

**Issue by VanshGarg06** [Vimall03/Alimento#160]
**Describe the bug**
The sign-in button on the Home Page is not working properly. When you click on the button, it does not redirect to the page for user login but downloads the source code of php into the local system.

**To Reproduce**
1. Go to Home Page
2. Click on Sign In in the navbar
3. See error: it will downloads the PHP file into the local system

**Expected behavior**
When clicking on the button of Sign In on the Home Page it will downloads the source code of the login page as user_login.php file into the local system.

**Screenshots**
![Alimento home page savoury alignment](https://github.com/user-attachments/assets/e13dedcb-d9e6-44fb-b17f-3f967d9be654)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single
 - Browser Google Chrome
 - Version 129.0.6668.101 (Official Build) (64-bit)

**Additional context**
The sign in button on the Home Page is not working it actually downloads the source code of the PHP file into the local system.
Please assign this issue to me under hacktoberfest and gssoc-ext with the necessary level 2 labels.

**Comment by Vimall03** [comment]
@VanshGarg06 Please update your fork. You are running a older version of the project. Also this is not a bug, since this is a php project you need to open the project using a Xampp / Wampp server to run it without errors.
