### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md 

### ISSUE THREAD

**Issue by amiya-cyber** [Vimall03/Alimento#162]
Issue Description
adding Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership
![2024-10-27](https://github.com/user-attachments/assets/66ac0101-ee99-49a2-af07-89311a28b00b)

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3
ASSIGN ME THE WORK
THANK YOU @Vimall03  !

**Comment by Vimall03** [comment]
Hey @amiya-cyber, as per the gssoc guidelines documentation changes will be assigned under level 1 only.
