### ISSUE TITLE
[FEAT] there is no any contributors page

### ISSUE THREAD

**Issue by SumitSahu44** [Vimall03/Alimento#163]
i will make a contributors page where you and other users can see all the contributos of these project like these : https://ticket-booking-blue.vercel.app/contributor.html

so assign this to me i will do it under level2

**Comment by Vimall03** [comment]
Hey @SumitSahu44 , I wont be able to give this level 2 since its a single page. Please let me know if you can do it under level 1.

**Comment by BhavikaPachauri** [comment]
I would like to solve this issue

**Comment by Vimall03** [comment]
@BhavikaPachauri, You can get started now

**Comment by BhavikaPachauri** [comment]
okk
