### ISSUE TITLE
[FEAT] Auto-Label Workflow for Pull Requests and Issues

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#167]
Description
I want to add a GitHub auto-label workflow that automatically assigns relevant labels, such as "gssoc-ext" and "hacktoberfest-accepted," to issues and pull requests related to these events. This will ensure more consistent tracking, better organization, and visibility of contributions linked to these important programs.

Key Features:
Automatic Labeling:
Automatically apply the "gssoc-ext" and "hacktoberfest-accepted" labels to pull requests and issues related to GSSOC Ext and Hacktoberfest.
Use Case:
Streamlines the labeling process by automating the assignment of labels for pull requests and issues, especially during events like GSSOC and Hacktoberfest.
Benefits:
Improved Efficiency: Reduces manual labeling efforts and ensures consistency.
Better Organization: Labels are applied systematically, making it easier to track event-specific contributions.
Enhanced Contributor Experience: Contributors receive immediate feedback through labels, improving their visibility within the project.

**Comment by Vimall03** [comment]
Hey @aditiverma-21 I think this already works, hacktober & gssoc labels are added by default when a new issue is opened. There's no need for a new workflow. Thankyou
