### ISSUE TITLE
[FEAT]Add login with google account option for fetching emails faster

### ISSUE THREAD

**Issue by sania-2912** [Vimall03/Alimento#171]
Adding a "Login with Google" option can significantly enhance the user experience by allowing users to quickly and securely access their accounts without manually entering their email. This integration leverages OAuth 2.0, a secure authentication standard provided by Google, enabling users to authenticate their identity with just a few clicks. By choosing to log in via Google, users bypass the need to remember complex passwords, and the app can immediately retrieve their verified email address, reducing input errors and speeding up the process. This option also adds a layer of security, as Google accounts are protected by robust security measures, including two-factor authentication.

**Comment by sania-2912** [comment]
@Vimall03 kindly assign me this issue

**Comment by BhavikaPachauri** [comment]
if this issue is open can i work on it

**Comment by Vimall03** [comment]
@sania-2912 You can get started now, I will assign the levels during the PR

**Comment by Vimall03** [comment]
@sania-2912 Have you made any progress ?

**Comment by sania-2912** [comment]
@Vimall03 yes, I it will be done by the end of the day

**Comment by sania-2912** [comment]
@Vimall03 I have added the code part however it will take a little time until it is testing and it looks fine. Thanks for understanding
