### ISSUE TITLE
[FEAT]User Loyalty Points System

### ISSUE THREAD

**Issue by Anushka-Pote** [Vimall03/Alimento#173]
**Is your feature request related to a problem? Please describe.**
Introduce a loyalty points system to reward users based on their order spending, which encourages repeat business and enhances customer retention.

**Describe the solution you'd implement**
Database Changes
New Table: user_points table to store user points data.
Trigger: award_points_after_order to update points in user_points based on order amount.

**Additional context**

Open Source- Hacktoberfest and GSSOC-Ext

**Comment by Vimall03** [comment]
Sounds cool, @Anushka-Pote You can get started now.
