### ISSUE TITLE
[FEAT]Want to add security

### ISSUE THREAD

**Issue by Dipanita45** [Vimall03/Alimento#174]
Please assign me the issue

**Comment by Vimall03** [comment]
Hey @Dipanita45, Please explain what you are planning on implementing ?

**Comment by Dipanita45** [comment]
I will add necessary security to protect the website against the harms

**Comment by Dipanita45** [comment]
Please assign me the issue

**Comment by Vimall03** [comment]
Can you specify how exactly ?

**Comment by Dipanita45** [comment]
Added the necessary security in the file for the website

**Comment by Dipanita45** [comment]
Please assign me

**Comment by Vimall03** [comment]
@Dipanita45 You have not given a clear explanation on what you will be doing exactly. I will assign this issue to you but please be aware that I will only merge the PR and assign levels if the work done adds value to the project. Thankyou for understanding
