### ISSUE TITLE
[FEAT] Refactoring Contributor's page

### ISSUE THREAD

**Issue by Sourabh782** [Vimall03/Alimento#190]
Current theme of contributor's page doesnt match with The sites theme.
current theme is king of too much colourful, which dont go with out site's design.

current: 
![image](https://github.com/user-attachments/assets/7b1d2596-7faa-4ef4-9b62-a019e0351049)

website:
![image](https://github.com/user-attachments/assets/c3ffae90-5d84-44c5-af15-26793e6a50b2)

improvement idea: i suggest implement minimal design look for contributor's page: 
something similar to this minimal design
![Screenshot 2024-11-04 213051](https://github.com/user-attachments/assets/316a2d02-637d-4e9a-b8d0-6f4518deb524)

**Comment by Vimall03** [comment]
@Sourabh782 You can get started

**Comment by Sourabh782** [comment]
> @Sourabh782 You can get started

Thx 👍, will make pr till Tommorow
