### ISSUE TITLE
[FEAT] Implementing vendor pages in NEXT JS

### ISSUE THREAD

**Issue by Sourabh782** [Vimall03/Alimento#199]
Implemeting pages related to vendor in next js, like home, add to menu, edit menu

**Comment by Vimall03** [comment]
Hey @Sourabh782, I have already assigned the migration to nextjs to a team of 3. The entire work has been divided amongst them. Assigning the migration work to any other contributor will cause confusions. Thankyou for understanding.

**Comment by Sourabh782** [comment]
> Hey @Sourabh782, I have already assigned the migration to nextjs to a team of 3. The entire work has been divided amongst them. Assigning the migration work to any other contributor will cause confusions. Thankyou for understanding.

Ohk nevermind I have created these issues assign to them 😊👍
