### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#2]
UI (User Interface) of your website and enhance user experience.

**Comment by Vimall03** [comment]
Hi @aditiverma-21, have you made any progress ?

**Comment by aditiverma-21** [comment]
Hello @Vimall03 I have been little busy today sorry for late response . I will add the ss and demo video soon.

**Comment by Vimall03** [comment]
Not an issue, take your time

**Comment by aditiverma-21** [comment]
https://github.com/user-attachments/assets/4c7e4d8a-c410-44c9-854c-86aba19b5744

@Vimall03 I added few updates.
