### ISSUE TITLE
Implement Customer Dashboard to the Next.js 

### ISSUE THREAD

**Issue by shubhagarwal1** [Vimall03/Alimento#235]
# Issue: Implement Customer Dashboard in Next.js

## Description
Develop a Customer Dashboard in Next.js to provide users with a personalized view of their order history and account details. The dashboard should be clean, responsive, and user-friendly, allowing customers to track their past orders and quickly reorder frequently purchased items.

### 1. Order History Overview
- Display a chronological list of past orders, with the most recent orders shown first.
- Each order entry should include:
  - **Order ID**
  - **Order date and time**
  - **Total amount**
  - **Order status** (e.g., Delivered, In Progress, Cancelled)
- Include an option to expand each order for detailed information.

### 2. Order Details View
- For each order, show itemized details such as:
  - **Food item names, descriptions, and quantities**
  - **Price per item and subtotal**
  - Any **special instructions** added by the customer
- Show **delivery address** and **payment method** used.

### 3. Reorder Feature
- Allow customers to reorder items from any previous order easily.
- Add a **“Reorder”** button next to each order or item, which automatically adds the items to the cart for quick checkout.

### 4. Favorites & Most Ordered Items
- Display the customer’s **most frequently ordered items** for quick access.
- Include an option to **add specific items to a “Favorites” list**.

### 5. Account Information
- Display basic account details (e.g., name, email, contact information).
- Allow customers to **update contact info and notification preferences** directly from the dashboard.

### 6. Responsive Design
- Ensure the dashboard is optimized for both **desktop and mobile views** with an adaptive, user-friendly layout.

### 7. UI/UX Enhancements
- Design a visually appealing interface with **clear typography** and a **modern layout**.
- Use consistent **spacing, buttons, and icons** to improve usability and coherence.

## Additional Considerations
- Use **Next.js API routes** to securely fetch order history and account details.
- Integrate **authentication** to restrict dashboard access to logged-in users.
- Handle data loading states with **loading indicators** to improve user experience.

---

By implementing these features, the Customer Dashboard will offer an organized and efficient way for users to manage their orders and account information, leading to improved user satisfaction and engagement.

**Comment by hardikguptaofficialgit** [comment]
Assign me this task !
