### ISSUE TITLE
Toggle dark mode

### ISSUE THREAD

**Issue by Aarnachauhan** [Vimall03/Alimento#24]
greeting to admin, 
i hope this message find u well , i see that in the project there is no dark mode option. i would like to add toggle dark mode to the project. 

best regards ,
Aarna chauhan 
2nd year student, NIT patna.

**Comment by Vimall03** [comment]
Hey @Aarnachauhan,Sounds good. please make sure that this feature works throughout the entire project.

**Comment by Aarnachauhan** [comment]
Sure!
Thank you admin .

Best regards

**Comment by Vimall03** [comment]
hey @Aarnachauhan, have you made any progress ?

**Comment by Aarnachauhan** [comment]
greeting to u sir . 
i have made the dark mode option but i am not getting desired output. its giving toggle dark mode to the website but the font colour of the text is not changing . I have been working really hard for that but i am unable to fix this. I am really sorry for this . can i submit it and anyone else can fix it? As u said i need to finish this in order to get started with  #26 hover issue. can i get assigned to #26 issue?
Thank you so much to give me a chance .I will be forever grateful . 
Best regards, 
Aarna.

**Comment by Vimall03** [comment]
@Aarnachauhan, Please don’t worry about the current challenges you're facing. If you're stuck, feel free to let me know, and there's no need to spend more time trying to fix it if it's proving difficult.

It seems like there might be some underlying UI issues on the homepage. If you'd like, you could redesign it from scratch, incorporating the hover effects and other enhancements you think would improve the user experience. If you're interested, I can elevate this task to a level 3 challenge, giving you the freedom to implement those design changes.

However, if you'd prefer to keep it simple, we can merge your current progress under level 1, and you can move on to the next issue.

Let me know how you'd like to proceed, and thank you again for your dedication.

**Comment by Aarnachauhan** [comment]
Thank you so much sir for your concern. 
could you please assign this issue as level 1 and i would like to move on to issue #26 .

**Comment by Vimall03** [comment]
cool, open a PR to merge your current progress before moving on to the next one.
