### ISSUE TITLE
[FEAT] DEPLOYMENT LINK

### ISSUE THREAD

**Issue by Meetpidev** [Vimall03/Alimento#248]
**Is your feature request related to a problem? Please describe.**
YES

**Describe the solution you'd implement**
DEPLOY IT IF NOT DEPLOYED YET AND ADD IT IN README.md FILE.. SO THAT WE DONT NEED TO SEE WEBSITE BY CLONING..

**Comment by Meetpidev** [comment]
@Vimall03 Want to help in deployment

**Comment by Meetpidev** [comment]
@Vimall03 can i do this ?

**Comment by Vimall03** [comment]
Hey @Meetpidev, You won't be able to deploy this project as you will need collaborator access to do it. We are currently migrating  the whole project to nextjs. Once that is completed I will deploy the project's link myself. Thankyou for understanding.
