### ISSUE TITLE
[FEAT] Adding feature cards with effects

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#25]
Feature Cards Layout: Each feature card will display a title, description, icon/image, and a CTA (Call to Action) button.
Hover Effects: Implement hover effects like shadow lifting, color changes, or subtle animations to make cards interactive.
Responsive Design: Ensure the feature cards are responsive for desktop and mobile views.
Transitions: Smooth transitions between hover and non-hover states for a seamless experience.

**Comment by Vimall03** [comment]
Hey @aditiverma-21, This seems like a duplicate of #2

I have already assigned you issue #2 with level-3 label.

**Comment by aditiverma-21** [comment]
Okay no worries
