### ISSUE TITLE
[FEAT] Nutrition and Allergen Information on it

### ISSUE THREAD

**Issue by sejals23** [Vimall03/Alimento#27]
Display detailed nutritional information for health-conscious customers.
Highlight any allergens present in each dish to ensure safety. This page provides detailed data about the nutritional content of each dish, helping customers make informed decisions about their meals.

**Comment by Vimall03** [comment]
Hey @sejals23, how are you planning to incorporate this feature ? Are you gonna be implementing it only on the frontend or both frontend & backend ?

**Comment by Vimall03** [comment]
@sejals23 Sounds good. I have assigned this issue to you,
