### ISSUE TITLE
[BUG]Contact Us form email functionality

### ISSUE THREAD

**Issue by BlitzIQ-Coder** [Vimall03/Alimento#29]
**The "send us email" functionality doesn't work in the contact form.** 

![Screenshot 2024-10-04 101537](https://github.com/user-attachments/assets/89018bf5-ac1b-4cd9-9ba3-46e7e2b5d4bb)

_I would love to work on this and make it work, as I have done a project previously just by using PHP and mySQL. So please assign this to me. If you are willing to please add **GSSOC and HACTOBERFEST** tags._

**Comment by Vimall03** [comment]
Hey @BlitzIQ-Coder, Sounds cool. you can start working on it. You can forward the emails to `aftereditofficial@gmail.com`

**Comment by BlitzIQ-Coder** [comment]
Thank you I'll need assist with few things, so where can i contact u personally?

**Comment by Vimall03** [comment]
Sure, Here's my linkedin - https://www.linkedin.com/in/vimall03/
