### ISSUE TITLE
Email Verification issues

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#3]
![image](https://github.com/user-attachments/assets/64dab09d-90d7-4feb-8691-08c65292994e)
Add Improved Verification Instructions
Provide a "Resend OTP" button for users who may not have received the email.
Notify users if they have successfully verified their email or if there was an error.
![image](https://github.com/user-attachments/assets/908aa2c0-69cf-4907-a912-8f288860788b)

**Comment by Vimall03** [comment]
@aditiverma-21 Im changing it to level 1 as the PR consisted frontend changes only.

**Comment by aditiverma-21** [comment]
okay thank you
