### ISSUE TITLE
[BUG]I encountered an error when trying to sign up in the application.Expected Behavior: The user should be signed up successfully. Actual Behavior: The signup fails with a database connection error.

### ISSUE THREAD

**Issue by sadafhukkeri** [Vimall03/Alimento#32]
I encountered an error when trying to sign up in the application. 
Expected Behavior: The user should be signed up successfully.
Actual Behavior: The signup fails with a database connection error.

**Comment by Vimall03** [comment]
Hey @sadafhukkeri, what is your approach to fix this issue ?

**Comment by BhavikaPachauri** [comment]
I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

**Comment by Vimall03** [comment]
This issue has been resolved in my recent commit. Thank you so much for your interest! If you notice any areas for improvement or additional fixes, please feel free to open a new issue.
