### ISSUE TITLE
[FEAT] UI Fix for Vendor's Home Page

### ISSUE THREAD

**Issue by Vimall03** [Vimall03/Alimento#34]
## Description:
The vendor's homepage requires a UI fix to improve its appearance and usability. The current UI needs refinement based on the screenshot provided below. Contributors are welcome to make changes or enhancements to the page. 

**Requirements:**
- Fix the UI issues on the vendor's homepage to make it cleaner and more user-friendly.
- You may need to adjust layout, font size, color schemes, and other stylistic elements to enhance the overall user experience.

## Steps to Reproduce:
1. Clone the project and set it up locally. (Refer setup section on the readme)
2. Navigate to the vendor's login page: `http://localhost/alimento/vendor/vendor_login.php`
3. Use the following credentials to access the vendor page:
   - **Email:** aftereditofficial@gmail.com
   - **Password:** Test@1234
4. Once logged in, review the vendor's homepage UI and note the issues that require fixing.
   
## Screenshot:

![image](https://github.com/user-attachments/assets/ec94be10-6f3e-4786-a085-3676b62ca565)

## Files Involved:
The relevant files for the vendor's page UI are located at:
`alimento/vendor`

## Notes:
- If you would like to create your own credentials or add a new restaurant, you are welcome to do so. This flexibility allows you to test the UI changes with different scenarios.
- Feel free to suggest any additional UI/UX improvements.

**Comment by BhavikaPachauri** [comment]
okk no problem i am interested

**Comment by BhavikaPachauri** [comment]
please assign me this task
