### ISSUE TITLE
[FEAT] UI Fix for Client's Home Page

### ISSUE THREAD

**Issue by Vimall03** [Vimall03/Alimento#35]
## Description:
The client's homepage requires a UI fix to improve its appearance and usability. The current UI needs to be updated based on the screenshot provided below. Contributors are welcome to enhance the design or fix any layout issues present. 

**Requirements:**
- Fix the UI issues on the client homepage to make it visually appealing and user-friendly.
- Consider updating layout, font, color schemes, and overall page styling to enhance the user experience.

## Steps to Reproduce:
1. Clone the project and set it up locally.
2. Navigate to the client's homepage: `http://localhost/alimento/home.php`
3. Use the following credentials for access if needed:
   - **Email:** aftereditofficial@gmail.com
   - **Password:** Test@1234
4. Once logged in, review the homepage UI and take note of areas needing improvement.

## Screenshot:
![image](https://github.com/user-attachments/assets/1f6b3004-2075-4dd6-a0d5-481b70f3cf63)

## Files Involved:
The relevant files for the client’s homepage UI are located at:
`alimento/home.php`

## Notes:
- If required, contributors can add new restaurants by signing up at `http://localhost/alimento/vendor/vendor_signup.php` and using the vendor panel to add restaurants.
- Alternatively, you can log in with the same credentials at `http://localhost/alimento/vendor/vendor_login.php` to add new restaurants.
- Feel free to suggest and implement any further UI/UX improvements.

**Comment by Web-Dev-Learner** [comment]
I like to work on this project, can u assign an issue to me

**Comment by Vimall03** [comment]
Hey @Web-Dev-Learner , Thank you for your interest in contributing to this project! Before you get started, could you please share the design you're aiming for? It would be great to see your vision before you begin working on it.

Looking forward to your ideas!

**Comment by Vimall03** [comment]
@Web-Dev-Learner, What's the progress ?

**Comment by Sourabh782** [comment]
Hii @Vimall03 may I work on it?

**Comment by Vimall03** [comment]
Closing this issue as duplicate of #43
