### ISSUE TITLE
Add Forget password buttons in login/signup page

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#4]
![image](https://github.com/user-attachments/assets/904ce235-27bf-428e-8d73-5c64d73dfe19)
Provide a "Forgot Password?" link that allows users to recover their passwords.
Validate both email and password fields on the client side to reduce unnecessary server requests.

**Comment by divya7202** [comment]
we should also add password in 8 character or hide or show password in these login page

**Comment by Vimall03** [comment]
Hi @divya7202 , Thank you for your interest in this issue! However, if you'd like to contribute to the repository, please make sure to open a new issue and get assigned to it first. You can also review the contribution guidelines here: [GSSoC Contribution Guidelines](https://gssoc.girlscript.tech/info).

As for the issue you mentioned, it will be addressed in issue #2

**Comment by divya7202** [comment]
should i open a new issue for this

**Comment by Vimall03** [comment]
No need to open a new issue for the one you're referring to 

> _( add password in 8 character or hide or show password in these login page )_ 

as it will be addressed in issue #2. If you're interested in contributing to something else, feel free to open a new issue, and I'd be happy to assign it to you.

**Comment by aditiverma-21** [comment]
Thank you @Vimall03
