### ISSUE TITLE
Website Not Deployed – Request for Deployment to Facilitate Contribution

### ISSUE THREAD

**Issue by SumitSahu44** [Vimall03/Alimento#48]
Hi  @Vimall03 

I hope you’re doing well. I’ve been exploring the repository and noticed that the project website is not deployed yet. This makes it challenging for contributors like myself to fully understand the functionality and user experience of the project, which could affect the quality and speed of contributions.

To help improve the project, I would like to suggest deploying the website so that contributors can easily interact with the live site and gain a better understanding of the existing problems and features.

If it's possible, I would be more than happy to take on this task and contribute by setting up the deployment. Could you kindly assign this issue to me?

Looking forward to contributing to this awesome project!

Best regards,
Sumit

**Comment by Vimall03** [comment]
Hi @SumitSahu44, that’s an important update we need. The reason the site isn’t currently hosted is that I’m unsure if any hosting service offers dynamic updates when the repository is updated. This is crucial to ensure the site stays current with new contributions.

Feel free to explore hosting options. I’ll assign this issue to you under level 3. However, if you're unable to host it, I won’t be able to assign a level, as the issue will remain unresolved. Please keep me updated on your progress.

**Comment by SumitSahu44** [comment]
Thank you @Vimall03  for assigning the issue to me. After evaluating the options, I suggest using Heroku for deploying the PHP website. Heroku supports PHP applications and integrates seamlessly with GitHub for automatic deployments. Here’s how it would work:

Next Steps:
1-Set up the Heroku app:
   I will create a Heroku app and configure it to support PHP.
  Add the appropriate database (MySQL or PostgreSQL) for the website.

2-Configure GitHub Auto Deployment:
   I will integrate Heroku with our GitHub repository so that every time a commit is pushed to the main branch, the site will automatically redeploy.

If this plan sounds good, I’ll proceed with setting up Heroku and integrating it with GitHub. Please let me know if you have any specific preferences for the database or any additional requirements.

**Comment by Vimall03** [comment]
Sounds good, but I'm not sure if you will be able to link this repo since it's not in your account.

**Comment by SumitSahu44** [comment]
yes, i think you need to deploy it

**Comment by Vimall03** [comment]
Cool. I'll look into it.

**Comment by SumitSahu44** [comment]
Ok or we have one alternative solution which is you can collab me with this repo so that i can connect with heroko

**Comment by Vimall03** [comment]
That wouldn't be possible as contributors cannot be given collaborator access as per the guidelines. I'll let you know what we can do further.

**Comment by SumitSahu44** [comment]
hey @Vimall03 any update or what should i do

**Comment by Vimall03** [comment]
Hey I looked into it. You're won't be able to host it as a contributor. Thankyou for your interest. 

Closing this issue as unplanned
