### ISSUE TITLE
[BUG] Sign in page missing

### ISSUE THREAD

**Issue by PATILYASHH** [Vimall03/Alimento#52]
**Is your feature request related to a problem? Please describe.**
There is no sign in page there is button but no any page lined to that icon

**Describe the solution you'd implement**
When user click on sign in button then user get UI for sign up / sign in to the website

**Describe alternatives you've considered**
I will build a responsive page for sign in process with some interesting animation and it will match theme of website also

**Comment by PATILYASHH** [comment]
please assign me for this issue

**Comment by Vimall03** [comment]
Hey @PATILYASHH, I'm not sure where exactly the sign in function is not working. I have checked the functionality and its working as expected. Please mention where you are facing this issue.

**Comment by PATILYASHH** [comment]
On my computer the single in button is not working if I click on that button then the sign in option is not coming, is this the problem of my pc or its problems with the website.

**Comment by Vimall03** [comment]
This looks like an issue on your end. The Sign in is working fine in the current code.



https://github.com/user-attachments/assets/2c373827-788b-4b25-b2aa-99cb9ba1c46a


I'm closing this issue as not planned. Thankyou for your interest in contributing to this project.

**Comment by PATILYASHH** [comment]
Sorry for this , I think it was my internet issue , sorry once again
