### ISSUE TITLE
[BUG]buttons not working

### ISSUE THREAD

**Issue by GauriSachan** [Vimall03/Alimento#55]
**Describe the bug**
Button Links: buttons don't click
Form Labels: want to Add label form inputs (name, email, message) to improve accessibility.
External Links: external links open in same page

**To Reproduce**

**Expected behavior**
.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
can you assign me this issue under the labes of the appropriate level, hacktoberfest and gssoc-ext

**Comment by Vimall03** [comment]
Hey @GauriSachan, You can get started. Please go through the entire project for such issues with button, not just the homepage. 
All the best!

**Comment by GauriSachan** [comment]
> Hey @GauriSachan, You can get started. Please go through the entire project for such issues with button, not just the homepage. All the best!

hey i was editing the code and i couldn't help but notice that in 1.html the types of food are not clickable >
what i wish to do:
make those options clickable
when user clicks those options then it will take them to a site with restaurants regarding that type of food (this will be for now but if you wish to add your own site you can easily change the site in the code)
so can i do it? if so then can you assign me other level if it seems fit?
