### ISSUE TITLE
[FEAT] Adding backend logic

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Vimall03/Alimento#56]
**Is your feature request related to a problem? Please describe.**

adding a local storage to store user Input.

<img width="1141" alt="Screenshot 2024-10-07 at 8 05 00 PM" src="https://github.com/user-attachments/assets/32e99e05-9796-4d25-87c7-204b957189c4">

**Comment by Vimall03** [comment]
@T-Rahul-prabhu-38, I'm not sure if we require that feature as all the details are currently being forwarded to an specific email. 
But I would love to listen to your approach for it. How are you planning to implement it ?

**Comment by T-Rahul-prabhu-38** [comment]
@Vimall03 shall i work on this.

**Comment by Vimall03** [comment]
cool, you can get started.

**Comment by T-Rahul-prabhu-38** [comment]
thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@Vimall03 i was actually wondering why the signin button results in a download , i thought it was a bug. 

on my laptop if i click on signin why does it download a php file.

**Comment by T-Rahul-prabhu-38** [comment]
i need help , how to run php files.

**Comment by Vimall03** [comment]
> @Vimall03 i was actually wondering why the signin button results in a download , i thought it was a bug.
> 
> on my laptop if i click on signin why does it download a php file.

I'm not sure how you are running the project in your local. You need to run PHP files on a xampp server.
