### ISSUE TITLE
[FEAT]want to add food items in 1.html

### ISSUE THREAD

**Issue by GauriSachan** [Vimall03/Alimento#60]
**Is your feature request related to a problem? Please describe.**
ey @Vimall03  i couldn't help but notice that in 1.html the types of food are not clickable >
what i wish to do:
make those options clickable
when user clicks those options then it will take them to a site with restaurants regarding that type of food (this will be for now but if you wish to add your own site you can easily change the site in the code)
can you assign me this? if so then can you the level which seems fit?

**Describe alternatives you've considered**

**Additional context**

**Comment by Vimall03** [comment]
@GauriSachan, the html file you are talking about needs to be removed, as it serves no purpose. I think it was added by a contributor accidentally. I will be removing the file in my next commit. 

closing this issue as not planned
