### ISSUE TITLE
[FEAT] Enhance Login/Register Page Usability and Fix Password Validation During Signup

### ISSUE THREAD

**Issue by ArchanRD** [Vimall03/Alimento#62]
**Describe the bug**
Password validation during signup is not working correctly. Instead of checking for password strength when a user is registering, the validation error ("`Password must be at least 8 characters long, include at least one uppercase letter, one lowercase letter, one digit, and one special character`") is only being displayed after the account is created and during login.

**To Reproduce**

1. Go to the signup page.
2. Enter a password that does not meet the validation criteria (e.g., a password shorter than 8 characters or missing special characters).
3. Complete the signup process.
4. Try logging in with the newly created account.
5. See the password validation error during login instead of at signup.

**Expected behavior**
Password validation should occur during the signup process before creating the account. The user should not be able to complete the registration unless the password meets the required criteria `(minimum 8 characters, including one uppercase letter, one lowercase letter, one digit, and one special character).`

**Screenshots**
## SignUp page ( Register )
![Screenshot from 2024-10-08 18-53-21](https://github.com/user-attachments/assets/d588ae63-39a0-4e63-b9eb-b694fd919fae)
A non-validated password is entered here.

## SignIn page ( Login )
![Screenshot from 2024-10-08 18-59-04](https://github.com/user-attachments/assets/eb28d761-c280-40cf-bb6c-3eebdc129cc8)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Brave]
 - Version [v1.70.119]

**Additional context**
This issue affects user experience by allowing weak passwords during signup, only to block them later during login. The validation logic should be moved to the signup form.

I would like to work on this issue under "hacktoberfest" and "gssoc-ext". I have done plenty projects using PHP, MySql, so I am 
 confident enough to solve this bug.

**Comment by Vimall03** [comment]
Good find @ArchanRD, You can get started now.

**Comment by ArchanRD** [comment]
Hey @Vimall03, I'd like to suggest a few enhancements that can be implemented alongside the original issue. These improvements would align well with the current pace of the project. Could you consider elevating this issue to a `level 2` priority and include the following enhancements?

1. **Show Password Button**: Add a "_**Show Password**_" toggle on the Login/Register page to enhance usability.

2. **Prevent Access to Login/Register Page After Login**: Once a user is logged in, they should not be able to access the **Login/Register** page. Implement a redirect to the home/dashboard page if the user is already authenticated.

3. **Post-SignUp Redirect**: After a successful signup, redirect the user directly to the home page instead of prompting them to log in again. This provides a smoother onboarding experience.

These features are standard across most websites and align with user expectations. The absence of these can negatively impact the overall user experience. Implementing these enhancements would make the authentication flow feel more polished and complete.

**Comment by Vimall03** [comment]
Hi @ArchanRD,

Thank you for your work so far. I believe the second point is already functional, but could you kindly double-check it to ensure everything is working as expected?

I'll update this to a level 2 issue for now. However, if all the promised features aren't fully implemented, I will only be able to merge it under level 1.
