### ISSUE TITLE
[FEAT]adding chatbot 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Vimall03/Alimento#63]
i want to add a chatbot which wil be tuned specifically to this website  @Vimall03 can you assign me this task.

**Comment by Vimall03** [comment]
Cool, will you implement the backed as well? Or just the frontend?

**Comment by T-Rahul-prabhu-38** [comment]
backend for chatbot?

**Comment by Vimall03** [comment]
Hi @Shalinis19137, What is your approach to implement the chatbot ?

**Comment by T-Rahul-prabhu-38** [comment]
it will be a chatbot built using gpt4o and this will be specific to the website so i can answer any questions related to the website too as well as general questions. It will work like a regular chatbot , the ones present on bottom right ususally.

**Comment by T-Rahul-prabhu-38** [comment]
yes , using js

**Comment by Vimall03** [comment]
okay, I'm not sure which level to assign this. Please complete your work. I will assign this issue an appropriate level while merging the PR.

**Comment by T-Rahul-prabhu-38** [comment]
sure. ill work on it

**Comment by Shalinis19137** [comment]
Basically it should be based on Frequent asked questions and some part of data clustering so ,I am going to do combo of this as my knowledge.
