### ISSUE TITLE
Fix Non-Functional Header Buttons and Unnecessary File Installations

### ISSUE THREAD

**Issue by Shweta-1902** [Vimall03/Alimento#64]
Resolve the issue where 'Concept,' 'About,' and 'Sign In' buttons in the header are not navigating to any sections. Ensure each button correctly redirects to the intended page or section. Additionally, investigate and remove unnecessary files being installed during deployment or updates
please assign this to me under the label of gssoc ext and hactoberfest
![Screenshot (390)](https://github.com/user-attachments/assets/1331ecd5-ce4a-4cb8-aeb4-ca44fe76c5f0)

**Comment by Vimall03** [comment]
Hey @Shweta-1902, You can get started
