### ISSUE TITLE
[BUG] The original Twitter and Facebook logo isnt displaying

### ISSUE THREAD

**Issue by TusharNaugain** [Vimall03/Alimento#69]
<img width="1440" alt="Screenshot 2024-10-10 at 1 38 40 AM" src="https://github.com/user-attachments/assets/758d6e2d-9b9e-4063-9eb3-ba54aceedcb2">

The original Twitter and Facebook logo wasn't displaying because the provided URL was either broken or not properly accessible, causing the image to fail to load.

**Comment by Vimall03** [comment]
Hi @TusharNaugain, The rendering of social media logo and the button just below the  navbar seems like a bug.
It would be great if you can move the social media icons to the footer and remove the button just below the navbar. 

This is what I'm expecting to see:

![image](https://github.com/user-attachments/assets/2ba4f8b5-8983-4511-8038-48cd098618ef)

**Comment by TusharNaugain** [comment]
please add the label of hactoberfest and Gssoc!

**Comment by Vimall03** [comment]
I have already added it, re check

**Comment by TusharNaugain** [comment]
> I have already added it, re check

Yeah sorry and thank you for that! i have fixed that and send to the PR. you can check that!
