### ISSUE TITLE
#Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [Vimall03/Alimento#7]
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext & level1 Labels.

**Comment by Vimall03** [comment]
Hello @KiranBaliga , Thank you for your interest in contributing to this project! I have added the necessary labels, and you are welcome to proceed with your contribution.

**Comment by KiranBaliga** [comment]
@Vimall03 I have raised the PR. Please review and action accordingly. Please add the above labels to the PR as well. Thank you!
