### ISSUE TITLE
[FEAT] Add Metrics Table to README

### ISSUE THREAD

**Issue by neeru24** [Vimall03/Alimento#70]
### Issue: Add Metrics Table to README

It would enhance the README file significantly to include a table displaying key repository metrics such as the number of stars, forks, pull requests, and any other relevant statistics. This addition will make the repository more informative and visually appealing to users.

**Benefits:**

- Improves the overall presentation of the README.
- Encourages contributions by showcasing community involvement.

**Comment by Vimall03** [comment]
Hi @neeru24, You can get started.

**Comment by Vimall03** [comment]
Hey @neeru24 Have you made any progress ?

**Comment by neeru24** [comment]
> Hey @neeru24 Have you made any progress ? 

Yes, I'll make a PR today
