### ISSUE TITLE
[FEAT] pop up message

### ISSUE THREAD

**Issue by Codewithmeowmeow** [Vimall03/Alimento#71]
**Is your feature request related to a problem? Please describe.**
A pop up message welcoming user will appear whenever user will visit the website.

**Describe the solution you'd implement**
It will enhance the website and make it more creative.

**Describe alternatives you've considered**

**Additional context**

**Comment by Vimall03** [comment]
Hi @Codewithmeowmeow, I don't think this feature is necessary for the project. Is there anything else on your mind ?

**Comment by Vimall03** [comment]
Closing this issue as unplanned
