### ISSUE TITLE
[BUG] Update twitter icon

### ISSUE THREAD

**Issue by poorvikaa08** [Vimall03/Alimento#78]
The current display button for Twitter on the website still shows the old Twitter bird icon. Twitter has rebranded to "X" with a new logo, so this button should be updated to reflect the latest branding.

Screenshots 📸 
![image](https://github.com/user-attachments/assets/8fb1b021-d1ce-4ab1-89d7-36970cecc068)
![image](https://github.com/user-attachments/assets/0eff629a-b49e-4437-9116-083dbbaf36db)

@Vimall03 
Assign it to me under gssoc-ext and hacktoberfest.

**Comment by Vimall03** [comment]
@poorvikaa08 i think this can be done in your previously opened issue as this is not a significant one to open a new issue. 
Make this changes in issue #77 itself.
