### ISSUE TITLE
Adding: FAQ Section

### ISSUE THREAD

**Issue by siri-chandana-macha** [Vimall03/Alimento#79]
I propose adding a FAQ section to the Alimento website. This section should address common questions regarding **products**, **ordering**, **delivery**, **dietary concerns**,and  **payments**. The FAQ section should be easy to navigate, with expandable questions or a searchable list of topics.
       Adding a FAQ section would improve customer support efficiency and reduce repetitive inquiries. It would also help new customers quickly find relevant information.
        
kindly  please assign me this task under gssoc-extd, hacktoberfest-accepted and level1

**Comment by Vimall03** [comment]
@siri-chandana-macha what's the progress ?

**Comment by siri-chandana-macha** [comment]
I will complete it within a day
