### ISSUE TITLE
Add Setup Guidelines to the Repository

### ISSUE THREAD

**Issue by Vimall03** [Vimall03/Alimento#8]
It would be helpful to include detailed setup guidelines in the repository for new contributors. This documentation can guide users through the process of cloning the repo, installing dependencies, and running the project locally.

**Additional context:** Including clear setup instructions will help streamline the onboarding process for new contributors and reduce potential setup-related issues.

**Interested in contributing?** If anyone is interested in taking this on, please comment below, and I’ll be happy to assign you to this issue!

**Comment by Harshmhajn** [comment]
may i work on this issue?

**Comment by Vimall03** [comment]
Hi @Harshmhajn,Thank you for your interest in this issue! Yes, I will assign you this issue! Please ensure that you write proper documentation on how to set up the entire application, including the database. The `.sql` file is also available in the repository, which you can reference in your documentation.

**Comment by aditiverma-21** [comment]
@Vimall03 I'm interested. Please assign
