### ISSUE TITLE
Adding User Profile Section and Search Bar

### ISSUE THREAD

**Issue by Ashwanisingh7930** [Vimall03/Alimento#81]
I propose to contribute to this project by implementing two key features:

**User Profile Section:** Create a user profile section that allows users to update their address, profile name, password and see the order history.
**Search Bar:** Add a search bar to the homepage that enables users to search for dishes and restaurants.

**Implementation Plan:**
In the **home.php** file, where users are redirected upon login, create a **user profile section** that displays the **user's name** and a **dropdown menu** with options to update their profile information Like **Name**, **Address** , **Password**  and see the **Order History.**
I will have to add some new files like **profile.php**, **password.php** and **orders.php**. 

Design and implement a **search bar** on the **homepage** that allows users to search for dishes and restaurants.

@Vimall03
I would like to assign this issue to myself under **gssoc-ext**, **level3** and **hacktoberfest-accepted**.

**Comment by Ashwanisingh7930** [comment]
Assign this issue to me under **gssoc-ext**, **level3** and **hacktoberfest-accepted**.

**Comment by Vimall03** [comment]
Hey @Ashwanisingh7930, That would be a really good addition to the project. Please make sure that it doesn't interfere with the other functionality of the project. 
And one more requirement is make the UI visually appealing. Happy to give this level 3 :)
