### ISSUE TITLE
Adding scroll-to-top feature

### ISSUE THREAD

**Issue by AswaniBolisetti** [Vimall03/Alimento#82]
@Vimall03 I would like to add the scroll to top feature, could you please assign me this under gssoc-ext, hacktoberfest-accepted, level2

**Comment by Vimall03** [comment]
Hey @AswaniBolisetti, I'm sorry I can't assign this issue level 2 as this is not significant enough for a level 2 label. You can get started now. 
Thankyou for understanding!

**Comment by ArchanRD** [comment]
Hey @Vimall03 I guess this issue is solved! PR #94. You might forgot to close this.
