### ISSUE TITLE
Enhance contact us section

### ISSUE THREAD

**Issue by AswaniBolisetti** [Vimall03/Alimento#83]
@Vimall03 I would like to enhance the contact us section
could you please assign this under gssoc-ext, hacktoberfest-accepted, level2

**Comment by Vimall03** [comment]
Hi @AswaniBolisetti, I'll assign this to you after you open a PR for #82. This issue can't be given level 2 for the same reason mentioned in #82.

**Comment by itznayan** [comment]
please assign this issue to me .

**Comment by Sarthakkashyapp** [comment]
Hi @Vimall03 I would like to work on this issue.

**Comment by Vimall03** [comment]
Hey @Sarthakkashyapp, Thankyou for your interest in this repo. However this issue was opened by another contributor and I cannot assign this issue to you. If you would like to contribute to the repo please feel free to open a new issue.
Thankyou for understanding!

**Comment by Vimall03** [comment]
@AswaniBolisetti, You can get started with this issue.

**Comment by Sarthakkashyapp** [comment]
@Vimall03 where can I see the deployment link.

**Comment by ArchanRD** [comment]
@Vimall03 This is also solved and merged! #95. Please close this too.
