### ISSUE TITLE
Issue Title: "Add Chatbot Feature"

### ISSUE THREAD

**Issue by AswaniBolisetti** [Vimall03/Alimento#86]
@Vimall03 
Issue Description: I would like to add a chatbot feature to the website to enhance user support and engagement. The chatbot will provide instant assistance to users by answering common queries, offering guidance, and directing them to relevant sections of the site.

Please assign this issue to me under the labels: level3, gssoc-ext, and hacktoberfest-accepted.

**Comment by Vimall03** [comment]
Hi @AswaniBolisetti, we already have a fully working chatbot. Please start working on the issues assigned to you. You can open new issues after the PR for the assigned issues are merged.

Closing this as unplanned.
