### ISSUE TITLE
[Feat] Redesign UI of the Landing Page

### ISSUE THREAD

**Issue by poorvikaa08** [Vimall03/Alimento#91]
The current font size of the website is small, it would be better if we increase it as it enhances the text readability and user experience.

![image](https://github.com/user-attachments/assets/989d5311-7160-4c1f-b56e-a70b721515ab)
![image](https://github.com/user-attachments/assets/f20583d3-d9d1-4ce5-b5d4-6db2e489bf13)

**Comment by poorvikaa08** [comment]
@Vimall03

**Comment by Vimall03** [comment]
@poorvikaa08, Will you be able to do a complete redesign of the landing page (index.html file only)? If you are interested then I will assign it level 2.

**Comment by Vimall03** [comment]
Hi @Sarthakkashyapp,

Let's wait for a response from @poorvikaa08. If we don't hear back soon, I'll go ahead and assign the issue to you. In the meantime, feel free to open a new issue if you find something you'd like to contribute to.

Thank you!

**Comment by Sarthakkashyapp** [comment]
Okay @Vimall03 I'll definitely look for other issues.

**Comment by poorvikaa08** [comment]
@Vimall03 
I will create a separate index.html under new design. I’m ready to work on it.

**Comment by Vimall03** [comment]
@poorvikaa08 cool, I'll assign this issue to you. You can get started.

**Comment by Vimall03** [comment]
Please make sure the design is visually appealing. and the links for login and sign up is working. 
for signup - `href="user_signup.php" `
for login -  `href="user_login.php"`

**Comment by Vimall03** [comment]
Hi @poorvikaa08, Have you made any progress ?

**Comment by Vimall03** [comment]
Closing this issue since @poorvikaa08 is inactive.

**Comment by Sarthakkashyapp** [comment]
Hey @Vimall03 can you assign me this ?

**Comment by Vimall03** [comment]
Hi@Sarthakkashyapp, I have opened a new issue. Read the description of  #110  & comment on that issue if you are interested

**Comment by Sarthakkashyapp** [comment]
@Vimall03 I've commented.
