### ISSUE TITLE
[FEAT]Can add meal plans 

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [Vimall03/Alimento#97]
**Is your feature request related to a problem? Please describe.**
no particular meals mentioned according to food timings.

**Describe the solution you'd implement**
can add various meal plans for different meal timings

**Describe alternatives you've considered**
NA

**Additional context**
na

**Comment by Vimall03** [comment]
Hi @SanikaBhalerao1345, Could you explain more on this ? 
Also, how are you planning to implement this ? Will you be using the database and PHP scripts ?

**Comment by SanikaBhalerao1345** [comment]
Hii @Vimall03 srry for late reply but I would like to work upon its frontend part
